// GoDo Design System Tokens — derived from DESIGN.md

export const Colors = {
  light: {
    surface: '#faf8ff',
    surfaceDim: '#d9d9e5',
    surfaceBright: '#faf8ff',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#f3f3fe',
    surfaceContainer: '#ededf9',
    surfaceContainerHigh: '#e7e7f3',
    surfaceContainerHighest: '#e1e2ed',
    onSurface: '#191b23',
    onSurfaceVariant: '#434655',
    inverseSurface: '#2e3039',
    inverseOnSurface: '#f0f0fb',
    outline: '#737686',
    outlineVariant: '#c3c6d7',
    surfaceTint: '#0053db',
    primary: '#004ac6',
    onPrimary: '#ffffff',
    primaryContainer: '#2563eb',
    onPrimaryContainer: '#eeefff',
    inversePrimary: '#b4c5ff',
    secondary: '#712ae2',
    onSecondary: '#ffffff',
    secondaryContainer: '#8a4cfc',
    onSecondaryContainer: '#fffbff',
    tertiary: '#943700',
    onTertiary: '#ffffff',
    tertiaryContainer: '#bc4800',
    onTertiaryContainer: '#ffede6',
    error: '#ba1a1a',
    onError: '#ffffff',
    errorContainer: '#ffdad6',
    onErrorContainer: '#93000a',
    background: '#faf8ff',
    onBackground: '#191b23',
    surfaceVariant: '#e1e2ed',
    primaryFixed: '#dbe1ff',
    primaryFixedDim: '#b4c5ff',
    secondaryFixed: '#eaddff',
    secondaryFixedDim: '#d2bbff',
  },
  dark: {
    surface: '#111318',
    surfaceDim: '#111318',
    surfaceBright: '#37393f',
    surfaceContainerLowest: '#0c0e13',
    surfaceContainerLow: '#191b23',
    surfaceContainer: '#1d1f27',
    surfaceContainerHigh: '#282a31',
    surfaceContainerHighest: '#33353c',
    onSurface: '#e1e2ed',
    onSurfaceVariant: '#c3c6d7',
    inverseSurface: '#e1e2ed',
    inverseOnSurface: '#2e3039',
    outline: '#8d8f9f',
    outlineVariant: '#434655',
    surfaceTint: '#b4c5ff',
    primary: '#b4c5ff',
    onPrimary: '#002878',
    primaryContainer: '#2563eb',
    onPrimaryContainer: '#eeefff',
    inversePrimary: '#004ac6',
    secondary: '#d2bbff',
    onSecondary: '#3f008e',
    secondaryContainer: '#8a4cfc',
    onSecondaryContainer: '#fffbff',
    tertiary: '#ffb596',
    onTertiary: '#541e00',
    tertiaryContainer: '#bc4800',
    onTertiaryContainer: '#ffede6',
    error: '#ffb4ab',
    onError: '#690005',
    errorContainer: '#93000a',
    onErrorContainer: '#ffdad6',
    background: '#111318',
    onBackground: '#e1e2ed',
    surfaceVariant: '#434655',
    primaryFixed: '#dbe1ff',
    primaryFixedDim: '#b4c5ff',
    secondaryFixed: '#eaddff',
    secondaryFixedDim: '#d2bbff',
  },
};

export const Spacing = {
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  containerMargin: 20,
  gutter: 12,
};

export const BorderRadius = {
  sm: 4,
  DEFAULT: 8,
  md: 12,
  lg: 16,
  xl: 24,
  full: 9999,
};

export const Typography = {
  displayLg: {
    fontFamily: 'HankenGrotesk_700Bold',
    fontSize: 32,
    lineHeight: 40,
    letterSpacing: -0.64,
  },
  headlineMd: {
    fontFamily: 'HankenGrotesk_600SemiBold',
    fontSize: 24,
    lineHeight: 32,
    letterSpacing: -0.24,
  },
  titleSm: {
    fontFamily: 'Manrope_600SemiBold',
    fontSize: 18,
    lineHeight: 24,
  },
  bodyMd: {
    fontFamily: 'Manrope_400Regular',
    fontSize: 16,
    lineHeight: 24,
  },
  bodySm: {
    fontFamily: 'Manrope_400Regular',
    fontSize: 14,
    lineHeight: 20,
  },
  labelMono: {
    fontFamily: 'JetBrainsMono_500Medium',
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0.24,
  },
  caption: {
    fontFamily: 'Manrope_500Medium',
    fontSize: 12,
    lineHeight: 16,
  },
};
